#!/bin/bash

echo "════════════════════════════════════════════════════════════"
echo "  Women in Leadership Event - Setup Instructions"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "✨ What's Included:"
echo "   • Clean 3-step registration flow (Select → Form → Success)"
echo "   • Local Delegate (ZMW 8,500 - 26,300)"
echo "   • International Delegate (\$985 or \$1,750)"
echo "   • Sponsorship (ZMW 30,000 - 250,000)"
echo "   • Real-time price calculation"
echo "   • Comprehensive form validation"
echo "   • Success confirmation with registration numbers"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  STEP 1: Run SQL Migration"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Open your Supabase project"
echo "2. Go to SQL Editor"
echo "3. Copy and paste the SQL below:"
echo ""
echo "────────────────────────────────────────────────────────────"
cat db/migrations/003-women-leadership-event.sql
echo "────────────────────────────────────────────────────────────"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  STEP 2: Start Your Development Server"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Run: npm run dev"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  STEP 3: Test the Flow"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Visit: http://localhost:5000/events"
echo "2. Find: 'Women in Leadership and Governance Seminar 2026'"
echo "3. Click: 'Register Here'"
echo "4. Choose: Local Delegate / International / Sponsorship"
echo "5. Fill the form and submit"
echo "6. Get registration number & confirmation email"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  ✅ Setup Complete!"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "The event image is already in the hero carousel (first image)"
echo "All forms have proper validation and error handling"
echo "Ready for production! 🎉"
echo ""
