#!/bin/bash

# ==================================================================
# Alliance Procurement & Capacity Building - Production URL Setup
# ==================================================================
# This script helps configure production URLs for password reset
# and other authentication flows to work correctly in production.
# ==================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Script configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLIENT_ENV_FILE="${SCRIPT_DIR}/client/.env.local"
SERVER_ENV_FILE="${SCRIPT_DIR}/.env"

echo -e "${CYAN}"
echo "=================================================================="
echo "🚀 Alliance Procurement & Capacity Building"
echo "   Production URL Configuration Setup"
echo "=================================================================="
echo -e "${NC}"

echo -e "${BLUE}This script will help you configure your production URLs to fix"
echo -e "password reset redirects and authentication flows.${NC}"
echo ""

# Function to validate URL format
validate_url() {
    local url=$1
    if [[ $url =~ ^https?://[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
        return 0
    else
        return 1
    fi
}

# Function to prompt for input with validation
prompt_with_validation() {
    local prompt=$1
    local validation_func=$2
    local error_msg=$3
    local value

    while true; do
        read -p "$prompt" value
        if [ -z "$value" ]; then
            echo -e "${RED}❌ This field cannot be empty.${NC}"
            continue
        fi

        if [ -n "$validation_func" ] && ! $validation_func "$value"; then
            echo -e "${RED}❌ $error_msg${NC}"
            continue
        fi

        echo "$value"
        break
    done
}

# Function to create backup of existing env files
create_backup() {
    local file=$1
    if [ -f "$file" ]; then
        local backup_file="${file}.backup.$(date +%Y%m%d_%H%M%S)"
        cp "$file" "$backup_file"
        echo -e "${YELLOW}📄 Backed up existing file: $(basename "$file") → $(basename "$backup_file")${NC}"
    fi
}

echo -e "${CYAN}📝 Step 1: Collect Production Configuration${NC}"
echo "================================================"

# Get production domain
echo -e "${BLUE}Enter your production domain (e.g., https://alliance-events.com):${NC}"
PRODUCTION_URL=$(prompt_with_validation "Production URL: " validate_url "Please enter a valid URL (https://domain.com)")

# Get Supabase details
echo ""
echo -e "${BLUE}Enter your Supabase project details:${NC}"
SUPABASE_URL=$(prompt_with_validation "Supabase URL (e.g., https://abc123.supabase.co): " validate_url "Please enter a valid Supabase URL")

echo -e "${BLUE}Enter your Supabase Anonymous Key:${NC}"
read -p "Supabase Anon Key: " SUPABASE_ANON_KEY

echo -e "${BLUE}Enter your Supabase Service Role Key:${NC}"
read -s -p "Supabase Service Role Key: " SUPABASE_SERVICE_ROLE_KEY
echo ""

# Get API URL
echo ""
echo -e "${BLUE}Enter your backend API URL (e.g., https://api.alliance-events.com):${NC}"
API_URL=$(prompt_with_validation "API URL: " validate_url "Please enter a valid API URL")

# Get email service details
echo ""
echo -e "${BLUE}Email Service Configuration:${NC}"
read -p "Resend API Key: " RESEND_API_KEY
read -p "From Email (e.g., noreply@alliance-events.com): " FROM_EMAIL

echo ""
echo -e "${GREEN}✅ Configuration collected successfully!${NC}"

echo ""
echo -e "${CYAN}📁 Step 2: Create Environment Files${NC}"
echo "=========================================="

# Create client environment file
create_backup "$CLIENT_ENV_FILE"

mkdir -p "$(dirname "$CLIENT_ENV_FILE")"

cat > "$CLIENT_ENV_FILE" << EOF
# ==================================================================
# Client Environment Configuration - PRODUCTION
# ==================================================================
# Generated by setup-production-urls.sh on $(date)
# Alliance Procurement & Capacity Building Event Management System

# Production App URL (CRITICAL: Used for password reset redirects)
VITE_APP_URL=$PRODUCTION_URL

# Supabase Configuration
VITE_SUPABASE_URL=$SUPABASE_URL
VITE_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

# Supabase Storage Configuration
VITE_SUPABASE_EVIDENCE_BUCKET=registrations

# API Configuration
VITE_API_URL=$API_URL

# Environment
VITE_NODE_ENV=production

# ==================================================================
# IMPORTANT: After creating this file, you MUST also configure
# your Supabase project redirect URLs. See SUPABASE_AUTH_CONFIG.md
# ==================================================================
EOF

echo -e "${GREEN}✅ Created client environment file: $(basename "$CLIENT_ENV_FILE")${NC}"

# Create server environment file
create_backup "$SERVER_ENV_FILE"

cat > "$SERVER_ENV_FILE" << EOF
# ==================================================================
# Server Environment Configuration - PRODUCTION
# ==================================================================
# Generated by setup-production-urls.sh on $(date)
# Alliance Procurement & Capacity Building Event Management System

# Database Configuration
SUPABASE_URL=$SUPABASE_URL
SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY

# Email Service Configuration
RESEND_API_KEY=$RESEND_API_KEY
FROM_EMAIL=$FROM_EMAIL

# Server Configuration
PORT=3000
NODE_ENV=production

# Security Configuration
CORS_ORIGIN=$PRODUCTION_URL

# JWT Configuration (generate a secure secret for production)
JWT_SECRET=\$(openssl rand -base64 32)

# ==================================================================
# SECURITY NOTES:
# - Keep this file secure and never commit to version control
# - Rotate API keys regularly
# - Use strong, unique JWT secrets
# ==================================================================
EOF

echo -e "${GREEN}✅ Created server environment file: $(basename "$SERVER_ENV_FILE")${NC}"

echo ""
echo -e "${CYAN}🔐 Step 3: Supabase Configuration Required${NC}"
echo "============================================="

echo -e "${YELLOW}⚠️  CRITICAL: You must now configure your Supabase project!${NC}"
echo ""
echo -e "${BLUE}1. Go to your Supabase Dashboard:${NC}"
echo -e "   ${SUPABASE_URL/\/rest\/v1/}"
echo ""
echo -e "${BLUE}2. Navigate to: Settings → Authentication → URL Configuration${NC}"
echo ""
echo -e "${BLUE}3. Set Site URL to:${NC}"
echo -e "   ${GREEN}$PRODUCTION_URL${NC}"
echo ""
echo -e "${BLUE}4. Add these Redirect URLs:${NC}"
echo -e "   ${GREEN}$PRODUCTION_URL/reset-password${NC}"
echo -e "   ${GREEN}$PRODUCTION_URL/auth/callback${NC}"
echo -e "   ${YELLOW}http://localhost:3000/reset-password${NC} (for development)"
echo -e "   ${YELLOW}http://localhost:5173/reset-password${NC} (for development)"
echo ""

# Create quick reference file
cat > "${SCRIPT_DIR}/PRODUCTION_URLS.txt" << EOF
Production URLs Configuration - $(date)
=====================================

Production Domain: $PRODUCTION_URL
API URL: $API_URL
Supabase URL: $SUPABASE_URL

Supabase Configuration Required:
- Site URL: $PRODUCTION_URL
- Redirect URLs:
  * $PRODUCTION_URL/reset-password
  * $PRODUCTION_URL/auth/callback
  * http://localhost:3000/reset-password (dev)
  * http://localhost:5173/reset-password (dev)

Next Steps:
1. Configure Supabase URLs (see above)
2. Build and deploy frontend: cd client && npm run build
3. Deploy backend with new environment variables
4. Test password reset flow in production

EOF

echo -e "${GREEN}✅ Created reference file: PRODUCTION_URLS.txt${NC}"

echo ""
echo -e "${CYAN}🚀 Step 4: Deployment Commands${NC}"
echo "================================="

echo -e "${BLUE}Frontend Build & Deploy:${NC}"
echo -e "${YELLOW}cd client${NC}"
echo -e "${YELLOW}npm install${NC}"
echo -e "${YELLOW}npm run build${NC}"
echo -e "${YELLOW}# Deploy the 'dist' folder to your hosting provider${NC}"
echo ""

echo -e "${BLUE}Backend Deploy:${NC}"
echo -e "${YELLOW}npm install${NC}"
echo -e "${YELLOW}npm run build${NC}"
echo -e "${YELLOW}npm start${NC}"
echo -e "${YELLOW}# Or deploy to your hosting provider${NC}"
echo ""

echo -e "${CYAN}✅ Step 5: Testing${NC}"
echo "=================="

echo -e "${BLUE}After deployment, test the password reset flow:${NC}"
echo -e "1. ${YELLOW}Go to $PRODUCTION_URL/login${NC}"
echo -e "2. ${YELLOW}Click 'Forgot Password'${NC}"
echo -e "3. ${YELLOW}Enter an email and submit${NC}"
echo -e "4. ${YELLOW}Check email - links should point to $PRODUCTION_URL${NC}"
echo -e "5. ${YELLOW}Click reset link - should redirect to your site${NC}"
echo ""

echo -e "${CYAN}📋 Important Files Created:${NC}"
echo "=============================="
echo -e "${GREEN}✅ client/.env.local${NC} - Client environment variables"
echo -e "${GREEN}✅ .env${NC} - Server environment variables"
echo -e "${GREEN}✅ PRODUCTION_URLS.txt${NC} - Quick reference guide"
echo -e "${GREEN}✅ SUPABASE_AUTH_CONFIG.md${NC} - Detailed Supabase setup guide"
echo ""

echo -e "${CYAN}🔒 Security Reminders:${NC}"
echo "======================="
echo -e "${RED}❌ Never commit .env files to version control${NC}"
echo -e "${RED}❌ Never share your Service Role Key${NC}"
echo -e "${GREEN}✅ Use environment variables in your deployment platform${NC}"
echo -e "${GREEN}✅ Rotate API keys regularly${NC}"
echo -e "${GREEN}✅ Monitor your application logs${NC}"
echo ""

echo -e "${GREEN}"
echo "=================================================================="
echo "🎉 Production URL Setup Complete!"
echo "=================================================================="
echo -e "${NC}"

echo -e "${BLUE}Next Steps:${NC}"
echo -e "1. ${YELLOW}Configure Supabase URLs (see instructions above)${NC}"
echo -e "2. ${YELLOW}Deploy your application with new environment variables${NC}"
echo -e "3. ${YELLOW}Test password reset flow${NC}"
echo -e "4. ${YELLOW}Monitor for any issues${NC}"
echo ""

echo -e "${GREEN}Your Alliance Procurement system is now ready for production! 🚀${NC}"

# Make the reference file easily accessible
echo ""
echo -e "${CYAN}💡 Tip: Run 'cat PRODUCTION_URLS.txt' to see the configuration summary anytime.${NC}"
